Added Dockerfile for CentOs 8
FoundationDB/fdb-joshua pull request #33
Opened 2021-07-16 11:42 UTC by oleg68

https://github.com/FoundationDB/fdb-joshua/issues/32

My tests failed in CentOs 7 due the very old glibc version (2.17).

I adopted the dockerfile for CentOs 8.

2021-07-16 17:48 UTC, jzhou77 approved these changes

2021-10-01 20:44 UTC, sfc-gh-kmakino commented
I would prefer to have a single Docker file and branch the base OS based on a user input.

2021-10-01 20:54 UTC, sfc-gh-kmakino commented
Please try this:
```
ARG VERSION=7
FROM centos:$VERSION
ARG VERSION
CMD cat /etc/redhat-release
```

2021-10-01 20:55 UTC, sfc-gh-kmakino commented
... you can specify the version as `docker build --build-arg VERSION=8`

2021-10-01 22:00 UTC, ammolitor commented
I agree with he comment from @sfc-gh-kmakino, no need to duplicate the file if an ARG will do.

2021-10-01 22:05 UTC, jzhou77 requested changes
Remove my approval.

2022-07-27 13:22 UTC, oleg68 commented
The new PR #66 has been created instead of this one

2022-07-27 13:22 UTC, closed without merging